version: '3.8'

services:
  nodeapp:
    build: .
    container_name: node_app1
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "3001:3000"
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:

